CREATE TABLE AMOUNT_PER_TYPE_WINDOWED (
    TRANSACTION_TYPE VARCHAR PRIMARY KEY,
    WINDOW_START BIGINT, 
    WINDOW_END BIGINT, 
    TOTAL_AMOUNT DOUBLE PRECISION,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);

CREATE TABLE COUNT_NUMB_BUY_PER_PRODUCT (
    PRODUCT_ID VARCHAR PRIMARY KEY,
    TOTAL_QUANTITY INT,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);

CREATE TABLE TOTAL_PAR_TRANSACTION_TYPE (
    TRANSACTION_TYPE VARCHAR PRIMARY KEY,
    TOTAL_AMOUNT DOUBLE PRECISION,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);

CREATE TABLE TOTAL_SPENT_PER_USER_TRANSACTION_TYPE (
    KSQL_COL_0 VARCHAR PRIMARY KEY,
    TOTAL_SPENT DOUBLE PRECISION,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);

CREATE TABLE TOTAL_TRANSACTION_AMOUNT_PER_PAYMENT_METHOD (
    PAYMENT_METHOD VARCHAR PRIMARY KEY,
    TOTAL_AMOUNT DOUBLE PRECISION,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);

CREATE TABLE TRANSACTION_STATUS_EVOLUTION (
    TRANSACTION_ID VARCHAR PRIMARY KEY,
    LATEST_STATUS VARCHAR,
    INGESTION_TIME TIMESTAMP,  -- Timestamp de l'ingestion
    INGESTION_DATE DATE  -- Date d'ingestion
);
